// FLATLAND DIVERGENCE, generated by `cargo xtask vendor-fork`.
//
// Installs an identity vfs session before this crate's own test binary runs, so
// upstream's tests keep exercising the routed code instead of failing closed.
// `cfg(test)` means it is absent from every production build -- not disabled in
// one. See `plans/2026-08-18-uucore-fork.md`.

/// Installs the identity session before any test runs.
///
/// A constructor rather than a per-test call because upstream's test bodies are
/// not ours to edit (D13): the marker for a deliberate divergence belongs
/// outside the case.
#[ctor::ctor]
fn install_identity_session_for_tests() {
    let Ok(mounts) = brush_vfs::Policy::identity() else {
        return;
    };
    let mut session = brush_vfs::Session::new(std::sync::Arc::new(brush_vfs::Vfs::new(mounts)));
    if let Ok(cwd) = std::env::current_dir() {
        let _ = session.set_cwd(&cwd.to_string_lossy());
    }
    brush_vfs::ambient::install(session);
}
