//! The filesystem hosted effects, marshalled onto the session.
//!
//! Every function here has the same three-part shape: take the owned path
//! argument(s) as a `String` (which releases them — [`native_into_string`]),
//! call the session effect through [`effect`], and marshal the result into the
//! generated `Try` type. The `*_ok`/`*_err` constructors that build those types
//! are uniform — an `Ok`/`Err` tag over a value or an `IOErr` — so they are
//! generated by the macros below rather than written twenty times.

use core::mem::ManuallyDrop;

use crate::marshal::{
    effect, host, io_err, native_from_str, native_into_string, roc_bytes_from_slice,
    roc_bytes_into_vec, rocstr_into_string,
};
use crate::roc_platform_abi::{
    DirOrFileOrOtherOrSymLink, HostDirCreateResult, HostDirCreateResultPayload,
    HostDirCreateResultTag, HostDirListResult, HostDirListResultPayload, HostDirListResultTag,
    HostFileDeleteResult, HostFileDeleteResultPayload, HostFileDeleteResultTag,
    HostFileIsExecutableResult, HostFileIsExecutableResultPayload, HostFileIsExecutableResultTag,
    HostFileReadBytesResult, HostFileReadBytesResultPayload, HostFileReadBytesResultTag,
    HostFileReadUtf8Result, HostFileReadUtf8ResultPayload, HostFileReadUtf8ResultTag,
    HostFileSizeInBytesResult, HostFileSizeInBytesResultPayload, HostFileSizeInBytesResultTag,
    HostFileTimeAccessedResult, HostFileTimeAccessedResultPayload, HostFileTimeAccessedResultTag,
    HostPathCanonicalizeResult, HostPathCanonicalizeResultPayload, HostPathCanonicalizeResultTag,
    HostPathTypeResult, HostPathTypeResultPayload, HostPathTypeResultTag, IOErr, RocList,
    RocListWith, RocStr, UnixBytesOrUtf8OrWindowsU16s as Native,
};
use brush_platform::{PathKind, PlatformEffects};

// A result type whose `Ok` carries a value and whose `Err` carries an `IOErr`.
// Generates `<lc>_ok(value) -> Ty` and `<lc>_err(IOErr) -> Ty`.
macro_rules! io_value_result {
    ($ok_fn:ident, $err_fn:ident, $ty:ident, $tag:ident, $payload:ident, $ok_ty:ty) => {
        fn $ok_fn(value: $ok_ty) -> $ty {
            $ty {
                payload: $payload {
                    ok: ManuallyDrop::new(value),
                },
                tag: $tag::Ok,
            }
        }
        fn $err_fn(error: IOErr) -> $ty {
            $ty {
                payload: $payload {
                    err: ManuallyDrop::new(error),
                },
                tag: $tag::Err,
            }
        }
    };
}

// A result type whose `Ok` is unit and whose `Err` carries an `IOErr`.
macro_rules! io_unit_result {
    ($ok_fn:ident, $err_fn:ident, $ty:ident, $tag:ident, $payload:ident) => {
        fn $ok_fn() -> $ty {
            $ty {
                payload: $payload { ok: [] },
                tag: $tag::Ok,
            }
        }
        fn $err_fn(error: IOErr) -> $ty {
            $ty {
                payload: $payload {
                    err: ManuallyDrop::new(error),
                },
                tag: $tag::Err,
            }
        }
    };
}

io_unit_result!(
    dir_ok,
    dir_err,
    HostDirCreateResult,
    HostDirCreateResultTag,
    HostDirCreateResultPayload
);
io_unit_result!(
    file_ok,
    file_err,
    HostFileDeleteResult,
    HostFileDeleteResultTag,
    HostFileDeleteResultPayload
);
io_value_result!(
    dir_list_ok,
    dir_list_err,
    HostDirListResult,
    HostDirListResultTag,
    HostDirListResultPayload,
    RocList<Native>
);
io_value_result!(
    read_bytes_ok,
    read_bytes_err,
    HostFileReadBytesResult,
    HostFileReadBytesResultTag,
    HostFileReadBytesResultPayload,
    RocListWith<u8, false>
);
io_value_result!(
    read_utf8_ok,
    read_utf8_err,
    HostFileReadUtf8Result,
    HostFileReadUtf8ResultTag,
    HostFileReadUtf8ResultPayload,
    RocStr
);
io_value_result!(
    bool_ok,
    bool_err,
    HostFileIsExecutableResult,
    HostFileIsExecutableResultTag,
    HostFileIsExecutableResultPayload,
    bool
);
io_value_result!(
    size_ok,
    size_err,
    HostFileSizeInBytesResult,
    HostFileSizeInBytesResultTag,
    HostFileSizeInBytesResultPayload,
    u64
);
io_value_result!(
    time_ok,
    time_err,
    HostFileTimeAccessedResult,
    HostFileTimeAccessedResultTag,
    HostFileTimeAccessedResultPayload,
    u128
);
io_value_result!(
    path_type_ok,
    path_type_err,
    HostPathTypeResult,
    HostPathTypeResultTag,
    HostPathTypeResultPayload,
    DirOrFileOrOtherOrSymLink
);

// `path_canonicalize`'s error is unit — the caller reports its own message — so
// it does not fit the `IOErr` macros.
fn canonicalize_ok(value: Native) -> HostPathCanonicalizeResult {
    HostPathCanonicalizeResult {
        payload: HostPathCanonicalizeResultPayload {
            ok: ManuallyDrop::new(value),
        },
        tag: HostPathCanonicalizeResultTag::Ok,
    }
}
fn canonicalize_err() -> HostPathCanonicalizeResult {
    HostPathCanonicalizeResult {
        payload: HostPathCanonicalizeResultPayload { err: [] },
        tag: HostPathCanonicalizeResultTag::Err,
    }
}

/// Resolves one owned path argument, short-circuiting to `$err` on an
/// unnameable path (D45) with the argument already released.
macro_rules! path_arg {
    ($arg:expr, $host:expr, $err:ident) => {
        match native_into_string($arg, $host) {
            Ok(path) => path,
            Err(error) => return $err(io_err(&error, $host)),
        }
    };
}

// --- Directories -----------------------------------------------------------

#[unsafe(no_mangle)]
pub extern "C" fn hosted_dir_create(path: Native) -> HostDirCreateResult {
    let host = host();
    let path = path_arg!(path, &host, dir_err);
    match effect(|s| s.dir_create(&path)) {
        Ok(()) => dir_ok(),
        Err(error) => dir_err(io_err(&error, &host)),
    }
}

#[unsafe(no_mangle)]
pub extern "C" fn hosted_dir_create_all(path: Native) -> HostDirCreateResult {
    let host = host();
    let path = path_arg!(path, &host, dir_err);
    match effect(|s| s.dir_create_all(&path)) {
        Ok(()) => dir_ok(),
        Err(error) => dir_err(io_err(&error, &host)),
    }
}

#[unsafe(no_mangle)]
pub extern "C" fn hosted_dir_delete_empty(path: Native) -> HostDirCreateResult {
    let host = host();
    let path = path_arg!(path, &host, dir_err);
    match effect(|s| s.dir_delete_empty(&path)) {
        Ok(()) => dir_ok(),
        Err(error) => dir_err(io_err(&error, &host)),
    }
}

#[unsafe(no_mangle)]
pub extern "C" fn hosted_dir_delete_all(path: Native) -> HostDirCreateResult {
    let host = host();
    let path = path_arg!(path, &host, dir_err);
    match effect(|s| s.dir_delete_all(&path)) {
        Ok(()) => dir_ok(),
        Err(error) => dir_err(io_err(&error, &host)),
    }
}

#[unsafe(no_mangle)]
pub extern "C" fn hosted_dir_list(path: Native) -> HostDirListResult {
    let host = host();
    let path = path_arg!(path, &host, dir_list_err);
    match effect(|s| s.dir_list(&path)) {
        Ok(entries) => {
            let list = unsafe { RocList::<Native>::allocate(entries.len(), &host) };
            for (index, entry) in entries.iter().enumerate() {
                unsafe {
                    list.elements
                        .add(index)
                        .write(native_from_str(entry, &host));
                }
            }
            dir_list_ok(list)
        }
        Err(error) => dir_list_err(io_err(&error, &host)),
    }
}

// --- Files -----------------------------------------------------------------

#[unsafe(no_mangle)]
pub extern "C" fn hosted_file_read_bytes(path: Native) -> HostFileReadBytesResult {
    let host = host();
    let path = path_arg!(path, &host, read_bytes_err);
    match effect(|s| s.file_read_bytes(&path)) {
        Ok(bytes) => read_bytes_ok(roc_bytes_from_slice(&bytes, &host)),
        Err(error) => read_bytes_err(io_err(&error, &host)),
    }
}

#[unsafe(no_mangle)]
pub extern "C" fn hosted_file_read_utf8(path: Native) -> HostFileReadUtf8Result {
    let host = host();
    let path = path_arg!(path, &host, read_utf8_err);
    match effect(|s| s.file_read_utf8(&path)) {
        Ok(text) => read_utf8_ok(RocStr::from_str(&text, &host)),
        Err(error) => read_utf8_err(io_err(&error, &host)),
    }
}

#[unsafe(no_mangle)]
pub extern "C" fn hosted_file_write_bytes(
    path: Native,
    bytes: RocListWith<u8, false>,
) -> HostFileDeleteResult {
    let host = host();
    // Both arguments are owned; take the bytes first (releasing them), then the
    // path, so neither leaks on the unnameable-path early return.
    let contents = roc_bytes_into_vec(bytes, &host);
    let path = path_arg!(path, &host, file_err);
    match effect(|s| s.file_write_bytes(&path, &contents)) {
        Ok(()) => file_ok(),
        Err(error) => file_err(io_err(&error, &host)),
    }
}

#[unsafe(no_mangle)]
pub extern "C" fn hosted_file_write_utf8(path: Native, contents: RocStr) -> HostFileDeleteResult {
    let host = host();
    let contents = rocstr_into_string(contents, &host);
    let path = path_arg!(path, &host, file_err);
    match effect(|s| s.file_write_utf8(&path, &contents)) {
        Ok(()) => file_ok(),
        Err(error) => file_err(io_err(&error, &host)),
    }
}

#[unsafe(no_mangle)]
pub extern "C" fn hosted_file_delete(path: Native) -> HostFileDeleteResult {
    let host = host();
    let path = path_arg!(path, &host, file_err);
    match effect(|s| s.file_delete(&path)) {
        Ok(()) => file_ok(),
        Err(error) => file_err(io_err(&error, &host)),
    }
}

#[unsafe(no_mangle)]
pub extern "C" fn hosted_file_hard_link(original: Native, link: Native) -> HostFileDeleteResult {
    let host = host();
    let original = path_arg!(original, &host, file_err);
    let link = path_arg!(link, &host, file_err);
    match effect(|s| s.file_hard_link(&original, &link)) {
        Ok(()) => file_ok(),
        Err(error) => file_err(io_err(&error, &host)),
    }
}

#[unsafe(no_mangle)]
pub extern "C" fn hosted_file_rename(from: Native, to: Native) -> HostFileDeleteResult {
    let host = host();
    let from = path_arg!(from, &host, file_err);
    let to = path_arg!(to, &host, file_err);
    match effect(|s| s.file_rename(&from, &to)) {
        Ok(()) => file_ok(),
        Err(error) => file_err(io_err(&error, &host)),
    }
}

#[unsafe(no_mangle)]
pub extern "C" fn hosted_file_set_executable(
    path: Native,
    executable: bool,
) -> HostFileDeleteResult {
    let host = host();
    let path = path_arg!(path, &host, file_err);
    match effect(|s| s.file_set_executable(&path, executable)) {
        Ok(()) => file_ok(),
        Err(error) => file_err(io_err(&error, &host)),
    }
}

#[unsafe(no_mangle)]
pub extern "C" fn hosted_file_is_executable(path: Native) -> HostFileIsExecutableResult {
    let host = host();
    let path = path_arg!(path, &host, bool_err);
    match effect(|s| s.file_is_executable(&path)) {
        Ok(value) => bool_ok(value),
        Err(error) => bool_err(io_err(&error, &host)),
    }
}

#[unsafe(no_mangle)]
pub extern "C" fn hosted_file_is_readable(path: Native) -> HostFileIsExecutableResult {
    let host = host();
    let path = path_arg!(path, &host, bool_err);
    match effect(|s| s.file_is_readable(&path)) {
        Ok(value) => bool_ok(value),
        Err(error) => bool_err(io_err(&error, &host)),
    }
}

#[unsafe(no_mangle)]
pub extern "C" fn hosted_file_is_writable(path: Native) -> HostFileIsExecutableResult {
    let host = host();
    let path = path_arg!(path, &host, bool_err);
    match effect(|s| s.file_is_writable(&path)) {
        Ok(value) => bool_ok(value),
        Err(error) => bool_err(io_err(&error, &host)),
    }
}

#[unsafe(no_mangle)]
pub extern "C" fn hosted_file_size_in_bytes(path: Native) -> HostFileSizeInBytesResult {
    let host = host();
    let path = path_arg!(path, &host, size_err);
    match effect(|s| s.file_size_in_bytes(&path)) {
        Ok(value) => size_ok(value),
        Err(error) => size_err(io_err(&error, &host)),
    }
}

// The three time effects are deferred (D46): the session returns `Unsupported`,
// which marshals to the `Unsupported` `IOErr`. The path is still resolved and
// released first, so an unnameable path is `NotFound` as everywhere else.
#[unsafe(no_mangle)]
pub extern "C" fn hosted_file_time_accessed(path: Native) -> HostFileTimeAccessedResult {
    let host = host();
    let path = path_arg!(path, &host, time_err);
    match effect(|s| s.file_time_accessed(&path)) {
        Ok(value) => time_ok(value),
        Err(error) => time_err(io_err(&error, &host)),
    }
}

#[unsafe(no_mangle)]
pub extern "C" fn hosted_file_time_modified(path: Native) -> HostFileTimeAccessedResult {
    let host = host();
    let path = path_arg!(path, &host, time_err);
    match effect(|s| s.file_time_modified(&path)) {
        Ok(value) => time_ok(value),
        Err(error) => time_err(io_err(&error, &host)),
    }
}

#[unsafe(no_mangle)]
pub extern "C" fn hosted_file_time_created(path: Native) -> HostFileTimeAccessedResult {
    let host = host();
    let path = path_arg!(path, &host, time_err);
    match effect(|s| s.file_time_created(&path)) {
        Ok(value) => time_ok(value),
        Err(error) => time_err(io_err(&error, &host)),
    }
}

// --- Paths -----------------------------------------------------------------

#[unsafe(no_mangle)]
pub extern "C" fn hosted_path_type(path: Native) -> HostPathTypeResult {
    let host = host();
    let path = path_arg!(path, &host, path_type_err);
    match effect(|s| s.path_type(&path)) {
        Ok(kind) => path_type_ok(match kind {
            PathKind::Dir => DirOrFileOrOtherOrSymLink::Dir,
            PathKind::File => DirOrFileOrOtherOrSymLink::File,
            PathKind::SymLink => DirOrFileOrOtherOrSymLink::SymLink,
            PathKind::Other => DirOrFileOrOtherOrSymLink::Other,
        }),
        Err(error) => path_type_err(io_err(&error, &host)),
    }
}

#[unsafe(no_mangle)]
pub extern "C" fn hosted_path_canonicalize(path: Native) -> HostPathCanonicalizeResult {
    let host = host();
    // The error is unit here, so an unnameable path is simply the `Err` — the
    // caller renders its own message, as `basic-cli` documents.
    let path = match native_into_string(path, &host) {
        Ok(path) => path,
        Err(_) => return canonicalize_err(),
    };
    match effect(|s| s.path_canonicalize(&path)) {
        Ok(resolved) => canonicalize_ok(native_from_str(&resolved, &host)),
        Err(_) => canonicalize_err(),
    }
}
