//! Check commands for code quality validation.
//!
//! This module provides various code quality checks that can be run individually
//! or as part of a CI workflow. Each check wraps an external tool and provides
//! consistent error handling and verbose output.
//!
//! Some checks require additional tools to be installed:
//! - `cargo-deny`: Security/license auditing (`cargo install cargo-deny`)
//! - `cargo-udeps`: Unused dependency detection (`cargo install cargo-udeps`, requires nightly)
//! - `cargo-public-api`: Public API analysis (`cargo install cargo-public-api`, requires nightly)
//! - `typos`: Spelling checker (`cargo install typos-cli`)
//! - `zizmor`: GitHub workflow security scanner (`pip install zizmor`)
//! - `lychee`: Link checker (`cargo install lychee`)

use anyhow::{Context, Result};
use clap::Parser;
use xshell::{Shell, cmd};

/// Run code quality checks.
#[derive(Parser)]
pub enum CheckCommand {
    /// Check that the filesystem ban is switched on and complete.
    Ban,
    /// Check that the code compiles.
    Build,
    /// Check dependencies for security vulnerabilities and license compliance.
    Deps,
    /// Check code formatting.
    Fmt,
    /// Check for broken links in documentation.
    Links,
    /// Run clippy lints.
    Lint,
    /// Analyze public API for breaking changes (requires nightly).
    PublicApi,
    /// Check that generated schemas are up-to-date.
    Schemas,
    /// Check for spelling errors.
    Spelling,
    /// Check for unused dependencies (requires nightly).
    UnusedDeps,
    /// Check GitHub workflow files for security issues.
    Workflows,
    /// Check that exactly one `uucore` -- the fork -- is in the graph (D4).
    UucorePatch,
    /// Check that `coreutils.all` still resolves to the frozen uucore features (D4).
    UucoreFeatures,
    /// Run each fork's own upstream test suite, its health metric (D13).
    Forks,
}

/// Run a check command.
pub fn run(cmd: &CheckCommand, verbose: bool) -> Result<()> {
    let sh = Shell::new()?;

    match cmd {
        CheckCommand::Ban => check_ban(&sh, verbose),
        CheckCommand::Fmt => check_fmt(&sh, verbose),
        CheckCommand::Lint => check_lint(&sh, verbose),
        CheckCommand::Deps => check_deps(&sh, verbose),
        CheckCommand::UnusedDeps => check_unused_deps(&sh, verbose),
        CheckCommand::Build => check_build(&sh, verbose),
        CheckCommand::Schemas => check_schemas(&sh, verbose),
        CheckCommand::PublicApi => check_public_api(&sh, verbose),
        CheckCommand::Spelling => check_spelling(&sh, verbose),
        CheckCommand::Workflows => check_workflows(&sh, verbose),
        CheckCommand::Links => check_links(&sh, verbose),
        CheckCommand::UucorePatch => check_uucore_patch(&sh, verbose),
        CheckCommand::UucoreFeatures => check_uucore_features(&sh, verbose),
        CheckCommand::Forks => check_forks(&sh, verbose),
    }
}

fn check_fmt(sh: &Shell, verbose: bool) -> Result<()> {
    eprintln!("Checking code formatting...");

    // Not `--all`, which recurses into *path dependencies* and so reaches
    // `forks/`. The forks are excluded from the workspace for the same reason
    // they are excluded here: they are upstream code, generated by
    // `cargo xtask vendor-fork` and not maintained by hand (D13), so holding
    // them to this workspace's style asks a rebase to re-derive a formatting
    // decision nobody made. Their health metric is their own upstream suite,
    // which `cargo xtask check forks` runs.
    let members = workspace_members()?;
    let args: Vec<String> = std::iter::once("fmt".to_owned())
        .chain(["--check".to_owned()])
        .chain(members.iter().flat_map(|m| ["-p".to_owned(), m.clone()]))
        .collect();

    if verbose {
        eprintln!("Running: cargo {}", args.join(" "));
    }
    cmd!(sh, "cargo {args...}")
        .run()
        .context("Format check failed")?;
    eprintln!("Format check passed ({} member(s)).", members.len());
    Ok(())
}

/// The workspace's own packages, read from cargo rather than listed here.
///
/// A hard-coded list would rot silently in the direction that matters: a new
/// member simply would not be checked, and the gate would keep reporting
/// success. `--no-deps` restricts the output to the workspace, which is
/// exactly the set `--all` overshoots.
fn workspace_members() -> Result<Vec<String>> {
    let root = crate::common::find_workspace_root()?;
    let output = std::process::Command::new(env!("CARGO"))
        .args(["metadata", "--no-deps", "--format-version", "1"])
        .current_dir(&root)
        .output()
        .context("running cargo metadata")?;
    anyhow::ensure!(
        output.status.success(),
        "cargo metadata failed: {}",
        String::from_utf8_lossy(&output.stderr)
    );

    let metadata: serde_json::Value =
        serde_json::from_slice(&output.stdout).context("parsing cargo metadata")?;
    let members: Vec<String> = metadata["packages"]
        .as_array()
        .context("cargo metadata has no packages array")?
        .iter()
        .filter_map(|p| p["name"].as_str().map(ToOwned::to_owned))
        .collect();

    // A check that formats nothing passes. This is the one failure mode the
    // switch away from `--all` introduces, so it is asserted rather than
    // trusted.
    anyhow::ensure!(
        !members.is_empty(),
        "cargo metadata reported no workspace members, so the format check \
         would have run over nothing"
    );
    Ok(members)
}

fn check_lint(sh: &Shell, verbose: bool) -> Result<()> {
    eprintln!("Running clippy...");
    let args = lint_args(verbose);

    // Checked here, on the argv about to be used, rather than only from
    // `check_ban`. A guard that inspects some *other* assembly of the arguments
    // is defeated by shadowing whatever it inspects; this one cannot be, because
    // it is the same `args` that reaches `cargo` on the next line.
    assert_denies_warnings(&args)?;

    if verbose {
        eprintln!("Running: cargo {}", args.join(" "));
    }
    cmd!(sh, "cargo {args...}")
        .run()
        .context("Clippy check failed")?;
    eprintln!("Clippy check passed.");
    Ok(())
}

/// The exact argv the workspace lint runs, and the only place it is assembled.
///
/// The trailing `-D warnings` is load-bearing: `disallowed_methods` is
/// warn-by-default, so without it the filesystem ban reports every violation
/// and exits 0. Earlier guards over this were defeated four ways in review --
/// a comment naming the flags, a constant shadowed inside `check_lint`, a
/// second `fn check_lint` that the text search found first, and a splice
/// wrapped in `if env::var("CI").is_err()`. All four worked because the guard
/// read source text; [`check_lint_denies_warnings`] reads this function's
/// return value instead.
fn lint_args(verbose: bool) -> Vec<&'static str> {
    let mut args = vec!["clippy", "--workspace", "--all-features", "--all-targets"];
    if verbose {
        args.push("--verbose");
    }
    args.extend_from_slice(&["--", "-D", "warnings"]);
    args
}

/// Fails when `deny.toml`'s `wrappers` lists no longer describe the tree.
///
/// `cargo-deny` reports a `wrappers` entry that is not a real parent, and a real
/// parent that is not listed, as `unmatched-wrapper` and `unused-wrapper` --
/// **warnings**, so it exits 0 while saying the inventory is wrong.
///
/// That inventory is not decoration. Each entry records a dependency that is
/// knowingly unrouted, so a stale one is a claim about confinement that stopped
/// being true. It went stale exactly this way once already: `findutils` and
/// `uu_grep` became parents of `walkdir` and nothing failed.
fn assert_no_unmatched_wrappers(output: &str) -> Result<()> {
    let stale: Vec<&str> = output
        .lines()
        .filter(|l| l.contains("unmatched-wrapper") || l.contains("unused-wrapper"))
        .collect();
    anyhow::ensure!(
        stale.is_empty(),
        "deny.toml's wrappers no longer describe the tree ({} issue(s)). These are \
         warnings to cargo-deny, which exits 0, but each entry records a dependency \
         that is knowingly unrouted -- so a stale one is a confinement claim that \
         stopped being true:\n  {}",
        stale.len(),
        stale.join("\n  ")
    );
    Ok(())
}

/// Path of the crate that must fail to lint, relative to the workspace root.
const BAN_FIXTURE: &str = "xtask/fixtures/banned-fs-access";

/// Verify that the filesystem ban in `clippy.toml` is switched on and complete.
///
/// The ban has three ways of quietly ceasing to exist, and this checks all
/// three:
///
/// - An entry naming a path that does not resolve disables one ban almost
///   invisibly: clippy emits a plain warning rather than a lint, so
///   `-D warnings` does not escalate it and the build stays green. The fixture
///   uses every entry exactly once and must produce exactly one diagnostic per
///   entry.
///
///   The fixture is its own workspace, so its dependency graph is not the
///   workspace's: an entry can fire here and be inert in `brush-core` if the
///   crate or feature it names is absent there. That gap is not covered.
/// - A `clippy.toml` in a member crate shadows the root one outright rather
///   than merging with it, so there must be exactly one in the tree.
/// - `disallowed_methods` is a warn-by-default lint, so a CI invocation
///   without `-D warnings` reports it and exits 0 regardless.
fn check_ban(sh: &Shell, verbose: bool) -> Result<()> {
    eprintln!("Checking the filesystem ban...");
    let root = crate::common::find_workspace_root()?;

    // Exactly one clippy.toml: a member crate's would shadow the root's.
    let found = find_clippy_configs(&root)?;
    if found.len() != 1 {
        anyhow::bail!(
            "expected exactly one clippy.toml in the tree, found {}: {}",
            found.len(),
            found
                .iter()
                .map(|p| p.display().to_string())
                .collect::<Vec<_>>()
                .join(", ")
        );
    }

    let expected = banned_paths(&found[0])?;
    if expected.is_empty() {
        anyhow::bail!("clippy.toml declares no disallowed-methods; the ban is not switched on");
    }

    // Lint the positive control. It must fail, and it must name every entry.
    let fixture = root.join(BAN_FIXTURE);
    let manifest = fixture.join("Cargo.toml");
    if verbose {
        eprintln!("Running: cargo clippy on {}", fixture.display());
    }

    // Clippy caches by crate fingerprint, and the fixture's source rarely
    // changes even when clippy.toml does, so a stale result would pass the
    // check without linting anything.
    cmd!(sh, "cargo clean --manifest-path {manifest}")
        .quiet()
        .run()
        .context("Failed to clean the ban fixture")?;

    let output = cmd!(
        sh,
        "cargo clippy --manifest-path {manifest} --message-format short -- -D warnings"
    )
    .env("CLIPPY_CONF_DIR", &root)
    .ignore_status()
    .quiet()
    .read_stderr()
    .context("Failed to run clippy on the ban fixture")?;

    let mut counts: std::collections::BTreeMap<&str, usize> = expected
        .iter()
        .filter(|path| resolves_on_this_platform(path))
        .map(|path| (path.as_str(), 0usize))
        .collect();
    let mut unexpected = Vec::new();
    for reported in reported_paths(&output) {
        match counts.get_mut(reported) {
            Some(count) => *count += 1,
            None => unexpected.push(reported.to_owned()),
        }
    }

    let never_fired: Vec<&str> = counts
        .iter()
        .filter(|(_, count)| **count == 0)
        .map(|(path, _)| *path)
        .collect();
    if !never_fired.is_empty() {
        anyhow::bail!(
            "these bans produced no diagnostic -- either the path no longer resolves (clippy \
             ignores unresolvable entries silently) or {BAN_FIXTURE} does not use them:\n  {}",
            never_fired.join("\n  ")
        );
    }
    if !unexpected.is_empty() {
        anyhow::bail!(
            "{BAN_FIXTURE} tripped bans it does not declare a use for:\n  {}",
            unexpected.join("\n  ")
        );
    }

    // Every entry fired, so the fixture must have failed to lint. If it did
    // not, `-D warnings` is not reaching the invocation.
    if !output.contains("error") {
        anyhow::bail!(
            "the ban fixture reported diagnostics but clippy did not fail; \
             `-D warnings` is not taking effect"
        );
    }

    check_lint_denies_warnings()?;

    eprintln!("Ban check passed ({} entries, all firing).", counts.len());
    Ok(())
}

/// Verify that the workspace lint invocation actually denies warnings.
///
/// Inspects the argv [`lint_args`] returns. Reading the value rather than the
/// source is the point: a textual guard cannot tell an argument from a comment
/// about one, cannot see a shadowed constant, takes the first of two
/// identically-named functions, and is satisfied by a splice a condition skips.
/// Checks that the `uucore` fork reached the whole dependency graph (D4).
///
/// Two failure modes, both silent at compile time, which is why this is a check
/// rather than a convention.
///
/// A *partial* repoint leaves `uucore 0.10.0 (registry)` and
/// `uucore 0.10.0 (path)` in the graph together. Cargo permits that (different
/// sources are different packages) and the `uumain` seam does not catch it,
/// since it passes only `OsString` and `i32`. What breaks is process-global
/// state that silently splits in two: the localizer thread-local
/// `uucore::locale` sets, so a utility reading the other copy renders raw Fluent
/// keys; and `uucore::error::EXIT_CODE`, which the routing tests set across the
/// crate boundary and would then read back wrong.
///
/// A *dead* patch is the mirror image: cargo reports an unused `[patch]` as a
/// warning on stderr and still exits 0, so a stale path or a version bump that
/// no longer matches leaves every utility on the registry copy with nothing in
/// the exit status to say so.
/// Path of the frozen uucore feature list, relative to the workspace root.
const UUCORE_FEATURES: &str = "xtask/uucore-features.txt";

/// The features each fork's own suite is run under.
///
/// `uucore` needs an explicit list because its interesting modules are all
/// feature-gated and `--all-features` would pull in `selinux` and `openssl`,
/// which need system libraries CI does not have.
const FORK_TEST_FEATURES: &[(&str, &str)] = &[(
    "uucore",
    "fs,safe-traversal,safe-copy,backup-control,fsxattr,perms,checksum,fsext,\
     parser,format,mode,entries,pipes,buf-copy,process",
)];

/// Runs each fork's own upstream test suite (D13's health metric).
///
/// The forks are `exclude`d from the workspace, so `cargo test -p uucore` from
/// the root fails with "cannot be tested because it requires dev-dependencies
/// and is not a member of the workspace". Each is therefore tested as its own
/// standalone workspace.
///
/// Two consequences worth stating rather than discovering. `[patch]` does not
/// apply in that mode, so the dependency set under test is not exactly the
/// shipped one. And a fork inherits upstream's own failures: on a given host
/// some of these do not pass in the registry copy either, so the metric is
/// "did *we* change the count", which needs the pristine comparison a rebase
/// performs, not an absolute zero.
fn check_forks(sh: &Shell, verbose: bool) -> Result<()> {
    eprintln!("Running the forks' own test suites...");
    let root = crate::common::find_workspace_root()?;
    let forks_dir = root.join("forks");

    let mut names: Vec<String> = std::fs::read_dir(&forks_dir)
        .with_context(|| format!("reading {}", forks_dir.display()))?
        .flatten()
        .filter(|e| e.path().join("Cargo.toml").is_file())
        .map(|e| e.file_name().to_string_lossy().into_owned())
        .collect();
    names.sort();
    anyhow::ensure!(
        !names.is_empty(),
        "no forks found under {}",
        forks_dir.display()
    );

    for name in &names {
        let dir = forks_dir.join(name);
        let features = FORK_TEST_FEATURES
            .iter()
            .find(|(n, _)| n == name)
            .map(|(_, f)| *f);

        if verbose {
            eprintln!(
                "Testing fork {name} ({})",
                features.unwrap_or("default features")
            );
        }
        let _guard = sh.push_dir(&dir);

        // Compile the fork before asking what its tests did.
        //
        // `cargo test` builds only what it is about to run, and 20 of these
        // forks have nothing to run: upstream sets `[lib] test = false` when
        // its tests live in a workspace `tests/` directory, which the fork does
        // not vendor. For those, `cargo test` compiles *nothing at all* and
        // exits 0, so a fork could stop compiling entirely and still be counted
        // green. `--all-targets` asks for the lib and its `cfg(test)` build
        // regardless of that flag.
        let checked = cargo(sh, &["check", "--all-targets"], features)
            .with_context(|| format!("checking fork {name}"))?;
        let check_stderr = String::from_utf8_lossy(&checked.stderr);
        if verbose {
            eprint!("{check_stderr}");
        }
        if !checked.status.success() {
            anyhow::bail!(
                "fork {name} does not compile -- `cargo check --all-targets` exited with {}:\n{}",
                checked.status,
                tail(&check_stderr, 40),
            );
        }

        // `output` rather than `read`: the exit status is the only thing that
        // separates "the suite ran and some tests failed" from "the suite never
        // ran", and `read` discards it. Capturing stderr too keeps 52 forks'
        // build warnings out of the terminal -- the noise a real error has to
        // compete with -- and hands it back on the failure path below.
        let output = cargo(sh, &["test"], features)
            .with_context(|| format!("running fork {name}'s suite"))?;

        let stdout = String::from_utf8_lossy(&output.stdout);
        let stderr = String::from_utf8_lossy(&output.stderr);
        if verbose {
            eprint!("{stderr}");
        }

        let failed = parse_test_failures(&stdout);
        let known = known_failures(&dir);

        // A suite that never ran is not a suite that passed. `cargo test` exits
        // non-zero both for a failing test and for a fork that does not build,
        // and only the first is what `known-test-failures.txt` describes. The
        // discriminator is whether the run named a failing test: a build error
        // names none, so without this the fork counts as green while running
        // nothing at all. That is not hypothetical -- `forks/sed` sat behind a
        // passing gate with its whole suite uncompilable, because upstream's
        // own `ctor` dependency collided with the one `vendor-fork` injected.
        //
        // Checked before the known-failure comparison below, which a build
        // error would otherwise fail with a much more confusing message: every
        // entry in the list "now passes", because nothing ran.
        if !output.status.success() && failed.is_empty() {
            anyhow::bail!(
                "fork {name}'s suite did not run to completion: `cargo test` exited with \
                 {} but named no failing test, so this is a build or harness failure rather \
                 than a test result:\n{}",
                output.status,
                tail(&stderr, 40),
            );
        }

        let unexpected: Vec<&String> = failed.iter().filter(|t| !known.contains(*t)).collect();
        // D13's mirror rule: an entry that no longer fails is itself an error,
        // or the list quietly stops describing anything.
        let stale: Vec<&String> = known.iter().filter(|t| !failed.contains(*t)).collect();

        anyhow::ensure!(
            unexpected.is_empty(),
            "fork {name} has {} unexpected test failure(s) -- D13's health metric:\n  {}",
            unexpected.len(),
            unexpected
                .iter()
                .map(|t| t.as_str())
                .collect::<Vec<_>>()
                .join("\n  ")
        );
        anyhow::ensure!(
            stale.is_empty(),
            "fork {name} lists {} known failure(s) that now pass; remove them from \
             known-test-failures.txt:\n  {}",
            stale.len(),
            stale
                .iter()
                .map(|t| t.as_str())
                .collect::<Vec<_>>()
                .join("\n  ")
        );
        if verbose {
            eprintln!("  {name}: {} known failure(s), no new ones", known.len());
        }
    }

    eprintln!("Fork suites passed ({} forks).", names.len());
    Ok(())
}

/// The test paths a `cargo test` run reported as failures.
///
/// Read from the summary block rather than counted, so the check can say *which*
/// test is new rather than only that the number moved.
fn parse_test_failures(output: &str) -> Vec<String> {
    let mut out = Vec::new();
    let mut in_block = false;
    for line in output.lines() {
        if line.trim() == "failures:" {
            in_block = true;
            continue;
        }
        if in_block {
            let trimmed = line.trim();
            // The block ends at the blank line or the `test result:` summary.
            if trimmed.is_empty() || trimmed.starts_with("test result:") {
                in_block = false;
                continue;
            }
            // Skip the per-test stdout dumps, which are also under "failures:".
            if !trimmed.contains(' ') {
                out.push(trimmed.to_string());
            }
        }
    }
    out.sort();
    out.dedup();
    out
}

/// Runs a cargo subcommand in the shell's current directory, capturing both
/// streams and the exit status, with the fork's feature set appended if it has
/// one.
fn cargo(sh: &Shell, args: &[&str], features: Option<&str>) -> Result<std::process::Output> {
    let mut argv: Vec<String> = args.iter().map(|arg| (*arg).to_owned()).collect();
    if let Some(features) = features {
        argv.push("--features".to_owned());
        argv.push(features.to_owned());
    }
    Ok(cmd!(sh, "cargo {argv...}")
        .ignore_status()
        .quiet()
        .output()?)
}

/// The last `n` lines of `text`.
///
/// A build log is far too long to put in an error message whole, and the part
/// that says what went wrong is at the end.
fn tail(text: &str, n: usize) -> String {
    let lines: Vec<&str> = text.lines().collect();
    lines[lines.len().saturating_sub(n)..].join("\n")
}

/// A fork's recorded known-failing upstream tests.
fn known_failures(dir: &std::path::Path) -> Vec<String> {
    let path = dir.join("known-test-failures.txt");
    let Ok(text) = std::fs::read_to_string(&path) else {
        return Vec::new();
    };
    let mut out: Vec<String> = parse_feature_list(&text)
        .into_iter()
        .map(str::to_string)
        .collect();
    out.sort();
    out.dedup();
    out
}

/// Checks that `coreutils.all` still resolves to the uucore features the D4
/// triage was decided against.
///
/// The plan's route/leave table is only correct for a particular set of
/// compiled modules. Six modules with filesystem access -- `benchmark`,
/// `proc_info`, `selinux`, `smack`, `systemd_logind`, `uptime` -- are left
/// unrouted *because they are not built*, and they read `/proc`, `/sys` and
/// `/etc/mtab`. Enabling one, directly or by adding a utility that pulls it in,
/// would ship 29 unrouted sites with nothing else in the tree objecting.
///
/// This is a blunt instrument and is meant to be: it fires on any change,
/// including a benign one, so that the triage is re-read rather than assumed.
fn check_uucore_features(sh: &Shell, verbose: bool) -> Result<()> {
    eprintln!("Checking the resolved uucore feature set...");
    let root = crate::common::find_workspace_root()?;
    let expected_path = root.join(UUCORE_FEATURES);
    let expected = std::fs::read_to_string(&expected_path)
        .with_context(|| format!("reading {}", expected_path.display()))?;
    let expected: Vec<&str> = parse_feature_list(&expected);
    anyhow::ensure!(
        !expected.is_empty(),
        "{} lists no features; the guard would pass vacuously",
        expected_path.display()
    );

    let actual = resolved_uucore_features(sh, verbose)?;
    let actual: Vec<&str> = actual.lines().collect();

    if actual != expected {
        let added: Vec<&&str> = actual.iter().filter(|f| !expected.contains(f)).collect();
        let removed: Vec<&&str> = expected.iter().filter(|f| !actual.contains(f)).collect();
        anyhow::bail!(
            "the uucore feature set changed.\n  added:   {added:?}\n  removed: {removed:?}\n\n             This is a decision, not a diff: re-read the route/leave table in \n             plans/2026-08-18-uucore-fork.md, decide whether any newly compiled \n             module routes, then run `cargo xtask gen uucore-features`."
        );
    }

    eprintln!("uucore feature check passed ({} features).", expected.len());
    Ok(())
}

/// The feature names in a frozen list, ignoring comments and blanks.
fn parse_feature_list(text: &str) -> Vec<&str> {
    text.lines()
        .map(str::trim)
        .filter(|l| !l.is_empty() && !l.starts_with('#'))
        .collect()
}

/// The uucore features `coreutils.all` currently resolves to, newline-separated
/// and sorted.
pub(crate) fn resolved_uucore_features(sh: &Shell, verbose: bool) -> Result<String> {
    let args = [
        "tree",
        "-p",
        "brush-coreutils-builtins",
        "--features",
        "coreutils.all",
        "-e",
        "features",
    ];
    if verbose {
        eprintln!("Running: cargo {}", args.join(" "));
    }
    let out = cmd!(sh, "cargo {args...}")
        .read()
        .context("running cargo tree to resolve uucore features")?;

    let mut found: Vec<String> = out
        .lines()
        .filter_map(|line| {
            let rest = line.split("uucore feature \"").nth(1)?;
            rest.split('"').next().map(str::to_string)
        })
        .collect();
    found.sort();
    found.dedup();
    Ok(found.join("\n"))
}

fn check_uucore_patch(sh: &Shell, verbose: bool) -> Result<()> {
    eprintln!("Checking the uucore patch...");
    let root = crate::common::find_workspace_root()?;

    if verbose {
        eprintln!("Running: cargo metadata");
    }
    // `cargo metadata` resolves the graph the way a build would, and prints the
    // unused-patch warning on stderr if the patch missed.
    let output = std::process::Command::new(env!("CARGO"))
        .args(["metadata", "--format-version", "1"])
        .current_dir(&root)
        .output()
        .context("running cargo metadata")?;
    anyhow::ensure!(
        output.status.success(),
        "cargo metadata failed: {}",
        String::from_utf8_lossy(&output.stderr)
    );

    let stderr = String::from_utf8_lossy(&output.stderr);
    if stderr.contains("was not used in the crate graph") || stderr.contains("unused patch") {
        anyhow::bail!(
            "cargo reports the [patch] was not used -- every consumer is still on the \
             registry uucore, and cargo exits 0 while saying so:\n{stderr}"
        );
    }

    let metadata: serde_json::Value =
        serde_json::from_slice(&output.stdout).context("parsing cargo metadata")?;
    let packages = metadata["packages"]
        .as_array()
        .context("cargo metadata has no packages array")?;

    let uucores: Vec<&serde_json::Value> = packages
        .iter()
        .filter(|p| p["name"].as_str() == Some("uucore"))
        .collect();
    anyhow::ensure!(
        uucores.len() == 1,
        "expected exactly one uucore in the graph, found {}: {}",
        uucores.len(),
        uucores
            .iter()
            .map(|p| format!(
                "{} from {}",
                p["version"].as_str().unwrap_or("?"),
                p["source"].as_str().unwrap_or("a path")
            ))
            .collect::<Vec<_>>()
            .join(", ")
    );

    // A path dependency has a null `source`; the registry copy names one.
    anyhow::ensure!(
        uucores[0]["source"].is_null(),
        "the single uucore in the graph is the registry copy, not the fork; \
         the [patch.crates-io] entry in the root manifest is not taking effect"
    );

    let manifest = uucores[0]["manifest_path"].as_str().unwrap_or_default();
    anyhow::ensure!(
        manifest.contains("forks/uucore"),
        "uucore resolves to {manifest}, which is not the fork"
    );

    let _ = sh;
    eprintln!("uucore patch check passed (one uucore, from forks/uucore).");
    Ok(())
}

fn check_lint_denies_warnings() -> Result<()> {
    for verbose in [false, true] {
        assert_denies_warnings(&lint_args(verbose))?;
    }
    Ok(())
}

/// The predicate itself: this argv must deny warnings and must not take the
/// denial back.
fn assert_denies_warnings(args: &[&str]) -> Result<()> {
    {
        let Some(separator) = args.iter().position(|a| *a == "--") else {
            anyhow::bail!("the lint argv has no `--` separator: {args:?}");
        };
        let rustc_args = &args[separator + 1..];

        if !rustc_args.windows(2).any(|w| w == ["-D", "warnings"]) {
            anyhow::bail!(
                "the lint argv does not deny warnings: {args:?}; the filesystem ban would \
                 report violations and still exit 0"
            );
        }

        // Nothing after it may take the ban back: a later `-A` overrides an
        // earlier `-D`, so a trailing allow silently undoes the whole list.
        if let Some(allow) = rustc_args
            .iter()
            .position(|a| *a == "-A" || a.starts_with("--allow"))
        {
            anyhow::bail!(
                "the lint argv allows lints back at position {allow}: {args:?}; a later `-A` \
                 overrides `-D warnings`"
            );
        }
    }

    Ok(())
}

/// Whether a banned path can resolve on the platform running the check.
///
/// An entry that cannot resolve produces no diagnostic, which is normally the
/// failure this check exists to catch -- but a `nix::` path on Windows is
/// absent by design rather than by mistake. The alternative, one ban list per
/// platform, would put the Unix surface out of a Windows reader's sight.
fn resolves_on_this_platform(path: &str) -> bool {
    // `rustix::fs` is `cfg(not(windows))` as a whole, so it gates with the
    // rest of the Unix surface.
    const UNIX_ONLY: [&str; 4] = ["std::os::unix::", "nix::", "libc::", "rustix::fs::"];
    const WINDOWS_ONLY: [&str; 1] = ["std::os::windows::"];

    // Entries that are Unix but not *every* Unix. `nix` and `libc` expose
    // their whole surface everywhere and paper over the gaps; `rustix` gates
    // per function, so a handful of its bans can only fire on one platform.
    // Naming them here rather than dropping them keeps the ban complete on the
    // platform that has the call, instead of complete on neither.
    const NOT_ON_APPLE: [&str; 2] = ["rustix::fs::mknodat", "rustix::fs::mkfifoat"];
    const APPLE_ONLY: [&str; 2] = ["rustix::fs::fclonefileat", "rustix::fs::getpath"];
    const LINUX_ONLY: [&str; 1] = ["rustix::fs::statx"];

    if NOT_ON_APPLE.contains(&path) {
        return cfg!(unix) && !cfg!(target_vendor = "apple");
    }
    if APPLE_ONLY.contains(&path) {
        return cfg!(target_vendor = "apple");
    }
    if LINUX_ONLY.contains(&path) {
        return cfg!(target_os = "linux");
    }

    if UNIX_ONLY.iter().any(|prefix| path.starts_with(prefix)) {
        return cfg!(unix);
    }
    if WINDOWS_ONLY.iter().any(|prefix| path.starts_with(prefix)) {
        return cfg!(windows);
    }
    true
}

/// Returns every `clippy.toml` in the tree, ignoring build output.
fn find_clippy_configs(root: &std::path::Path) -> Result<Vec<std::path::PathBuf>> {
    fn walk(dir: &std::path::Path, found: &mut Vec<std::path::PathBuf>) -> Result<()> {
        for entry in dir.read_dir()? {
            let entry = entry?;
            let path = entry.path();
            let name = entry.file_name();
            if entry.file_type()?.is_dir() {
                if name == "target" || name == ".git" {
                    continue;
                }
                walk(&path, found)?;
            } else if name == "clippy.toml" || name == ".clippy.toml" {
                found.push(path);
            }
        }
        Ok(())
    }

    let mut found = Vec::new();
    walk(root, &mut found)?;
    found.sort();
    Ok(found)
}

/// Reads the banned method paths out of a `clippy.toml`.
fn banned_paths(config: &std::path::Path) -> Result<Vec<String>> {
    let text =
        std::fs::read_to_string(config).with_context(|| format!("reading {}", config.display()))?;
    let parsed: toml::Value =
        toml::from_str(&text).with_context(|| format!("parsing {}", config.display()))?;

    let Some(entries) = parsed
        .get("disallowed-methods")
        .and_then(toml::Value::as_array)
    else {
        return Ok(Vec::new());
    };

    Ok(entries
        .iter()
        .filter_map(|entry| match entry {
            toml::Value::String(path) => Some(path.clone()),
            other => other
                .get("path")
                .and_then(toml::Value::as_str)
                .map(ToOwned::to_owned),
        })
        .collect())
}

/// Extracts the method paths clippy named in its diagnostics.
fn reported_paths(output: &str) -> Vec<&str> {
    const MARKER: &str = "use of a disallowed method `";
    output
        .split(MARKER)
        .skip(1)
        .filter_map(|rest| rest.split('`').next())
        .collect()
}

fn check_deps(sh: &Shell, verbose: bool) -> Result<()> {
    eprintln!("Checking dependencies...");
    if verbose {
        eprintln!("Running: cargo deny --all-features check all");
    }
    // Captured rather than streamed, because the interesting failure is a
    // *warning*; see `assert_no_unmatched_wrappers`.
    let output = cmd!(sh, "cargo deny --all-features check all")
        .ignore_status()
        .read_stderr()
        .context("Failed to run cargo-deny")?;
    eprint!("{output}");
    anyhow::ensure!(!output.contains("error["), "Dependency check failed");

    assert_no_unmatched_wrappers(&output)?;
    check_vfs_has_no_features()?;

    eprintln!("Dependency check passed.");
    Ok(())
}

/// Verify that `brush-vfs` declares no cargo features.
///
/// A feature on the crate that decides what a path means is a second answer to
/// the same question: two builds of the shell would resolve differently, and
/// only one of them would be the one under test. "No features that alter
/// resolution" is only checkable as "no features", since nothing stops a
/// feature added for another reason from reaching resolution later.
fn check_vfs_has_no_features() -> Result<()> {
    let root = crate::common::find_workspace_root()?;
    let manifest = root.join("brush-vfs/Cargo.toml");
    let text = std::fs::read_to_string(&manifest)
        .with_context(|| format!("reading {}", manifest.display()))?;
    let parsed: toml::Value =
        toml::from_str(&text).with_context(|| format!("parsing {}", manifest.display()))?;

    let declared: Vec<&str> = parsed
        .get("features")
        .and_then(toml::Value::as_table)
        .map(|table| table.keys().map(String::as_str).collect())
        .unwrap_or_default();

    if declared.is_empty() {
        Ok(())
    } else {
        anyhow::bail!(
            "brush-vfs declares cargo features ({}); path resolution must not have build-time \
             variants",
            declared.join(", ")
        )
    }
}

fn check_unused_deps(sh: &Shell, verbose: bool) -> Result<()> {
    eprintln!("Checking for unused dependencies (requires nightly)...");
    if verbose {
        eprintln!("Running: cargo +nightly udeps --workspace --all-targets --all-features");
    }
    cmd!(
        sh,
        "cargo +nightly udeps --workspace --all-targets --all-features"
    )
    .run()
    .context("Unused dependency check failed")?;
    eprintln!("Unused dependency check passed.");
    Ok(())
}

fn check_build(sh: &Shell, verbose: bool) -> Result<()> {
    eprintln!("Checking that code compiles...");
    let mut args = vec!["check", "--all-features", "--all-targets", "--workspace"];
    if verbose {
        args.push("--verbose");
        eprintln!("Running: cargo {}", args.join(" "));
    }
    cmd!(sh, "cargo {args...}")
        .run()
        .context("Build check failed")?;

    check_cross_platform(sh, verbose)?;

    eprintln!("Build check passed.");
    Ok(())
}

/// Targets checked in addition to the host, and the crate set checked for them.
///
/// Not the whole workspace: `libfuzzer-sys` and `onig_sys` are C libraries that
/// need a cross toolchain the average dev box does not have, and `onig_sys`
/// arrives through `uu_expr`, so a workspace-wide cross check would fail on
/// setup rather than on code. These are the crates that carry the sandbox, which
/// is where a platform assumption actually costs something.
const CROSS_TARGETS: &[&str] = &["x86_64-pc-windows-gnu"];

/// Crates whose platform assumptions are worth catching before CI does.
const CROSS_CRATES: &[&str] = &[
    "brush-vfs",
    "brush-core",
    "brush-builtins",
    "brush-parser",
    "brush-interactive",
    "brush-shell",
    "brush-coreutils-builtins",
];

/// Checks the sandbox crates against non-host targets.
///
/// A native-only check is how `brush-vfs` came to not compile for Windows at
/// all: `std::os::fd` in a signature and a `libc` constant in an expression,
/// neither visible from macOS, both caught by CI or a user rather than by the
/// person who wrote them. Cross-checking is cheap next to that.
///
/// Skips with a warning when the target's std is not installed, rather than
/// failing: a contributor who has not run `rustup target add` should not be
/// blocked, and CI installs the targets it cares about.
fn check_cross_platform(sh: &Shell, verbose: bool) -> Result<()> {
    let installed = cmd!(sh, "rustup target list --installed")
        .quiet()
        .read()
        .unwrap_or_default();

    for target in CROSS_TARGETS {
        if !installed.lines().any(|l| l.trim() == *target) {
            eprintln!(
                "  skipping {target}: not installed (`rustup target add {target}` to enable)"
            );
            continue;
        }
        eprintln!("  checking {target}...");
        for krate in CROSS_CRATES {
            if verbose {
                eprintln!("    cargo check -p {krate} --target {target}");
            }
            cmd!(sh, "cargo check --quiet -p {krate} --target {target}")
                .run()
                .with_context(|| format!("{krate} does not compile for {target}"))?;
        }
    }
    Ok(())
}

fn check_schemas(sh: &Shell, verbose: bool) -> Result<()> {
    eprintln!("Checking generated schemas...");

    // Regenerate schemas to a temporary state to compare against committed versions.
    if verbose {
        eprintln!(
            "Running: cargo run --package xtask -- gen schema config --out schemas/config.schema.json"
        );
    }
    cmd!(
        sh,
        "cargo run --package xtask -- gen schema config --out schemas/config.schema.json"
    )
    .run()
    .context("Failed to regenerate schemas")?;

    // Check for drift by capturing the diff output.
    // We don't use --exit-code here because we want to capture and display the
    // actual differences to help the user understand what changed.
    if verbose {
        eprintln!("Running: git diff schemas/");
    }
    let diff_output = cmd!(sh, "git diff schemas/")
        .read()
        .context("Failed to run git diff on schemas directory")?;

    if !diff_output.is_empty() {
        // Show the user exactly what changed so they can understand the drift.
        eprintln!("\nSchema drift detected. The following changes were found:\n");
        eprintln!("{diff_output}");
        anyhow::bail!(
            "Generated schemas are out of date. Please run 'cargo xtask gen schema config --out schemas/config.schema.json' and commit the changes."
        );
    }

    eprintln!("Schema check passed.");
    Ok(())
}

fn check_public_api(sh: &Shell, verbose: bool) -> Result<()> {
    eprintln!("Analyzing public API (requires nightly and cargo-public-api)...");

    // This is typically only useful for PRs comparing against main
    if verbose {
        eprintln!("Running: cargo +nightly public-api --version");
    }
    cmd!(sh, "cargo +nightly public-api --version")
        .run()
        .context("cargo-public-api not installed. Install with: cargo install cargo-public-api")?;

    eprintln!("Public API analysis complete. For PR diffs, compare against main branch.");
    Ok(())
}

fn check_spelling(sh: &Shell, verbose: bool) -> Result<()> {
    eprintln!("Checking spelling...");
    if verbose {
        eprintln!("Running: typos");
    }
    cmd!(sh, "typos")
        .run()
        .context("Spelling check failed. Install typos with: cargo install typos-cli")?;
    eprintln!("Spelling check passed.");
    Ok(())
}

fn check_workflows(sh: &Shell, verbose: bool) -> Result<()> {
    eprintln!("Checking GitHub workflows for security issues...");
    if verbose {
        eprintln!("Running: zizmor .github/workflows/");
    }
    cmd!(sh, "zizmor .github/workflows/")
        .run()
        .context("Workflow check failed. Install zizmor with: pip install zizmor")?;
    eprintln!("Workflow check passed.");
    Ok(())
}

fn check_links(sh: &Shell, verbose: bool) -> Result<()> {
    eprintln!("Checking for broken links...");
    if verbose {
        eprintln!("Running: lychee --offline docs/");
    }
    cmd!(sh, "lychee --offline docs/")
        .run()
        .context("Link check failed. Install lychee with: cargo install lychee")?;
    eprintln!("Link check passed.");
    Ok(())
}
