//! `xtask vendor-fork <name>`: vendor a uutils crate and route it (D4/D13).
//!
//! Turns "fork the coreutils" into a repeatable operation: copy the pristine
//! upstream lib out of the cargo registry cache into `forks/<name>`, generate a
//! fork manifest (drop the binary and benches, add the `brush-vfs` dependency),
//! and run the codemod over it. The result is the same shape the hand-built
//! `uu_cat` fork has.
//!
//! It does *not* wire the fork into `brush-coreutils-builtins` -- that is a
//! one-line dependency repoint per utility, left as a deliberate step so a fork
//! is reviewed before it ships.

use std::path::{Path, PathBuf};

use anyhow::{Context, Result};

use crate::codemod::{self, CodemodCommand};

/// The `vendor-fork` subcommand.
#[derive(clap::Parser)]
pub struct VendorCommand {
    /// The crate name to vendor, e.g. `uu_head`.
    pub crate_name: String,

    /// Vendor this exact version rather than the newest cached one.
    #[clap(long)]
    pub version: Option<String>,

    /// Vendor and generate the manifest but do not run the codemod.
    #[clap(long)]
    pub no_codemod: bool,
}

/// The `brush-vfs` version the forks pin, matching the workspace crate.
const BRUSH_VFS_PATH: &str = "../../brush-vfs";

/// Where the forked `uucore` keeps the per-utility locale files it embeds.
const VENDORED_LOCALES: &str = "forks/uucore/locales/utils";

/// The `vendor-locales` subcommand.
///
/// Upstream's `uucore` embeds each utility's Fluent catalog at compile time by
/// scanning its *sibling registry directory* for `uu_<util>-<version>` — a
/// layout `forks/uucore` cannot reproduce, since its siblings are the five leaf
/// forks and carry no version suffix. The result is not a build error: the
/// crate's own `uucore/en-US.ftl` still loads, so the bundle has `common-error`,
/// so localization reports success and every utility-specific message renders as
/// a raw Fluent key with a correct exit code.
///
/// So the fork carries the catalogs itself, regenerated by this command, and its
/// build script reads them from a fixed path instead of guessing at a directory
/// layout. That also severs a dependency on the registry cache being warm:
/// before this, the strings a build embedded came from whichever `uu_*` crates
/// happened to be unpacked on the machine — including ones the workspace no
/// longer depends on.
#[derive(clap::Parser)]
pub struct VendorLocalesCommand {
    /// Take catalogs from this crate version rather than the newest cached one.
    #[clap(long, default_value = "0.10.0")]
    pub version: String,

    /// Report what would change without writing anything.
    #[clap(long)]
    pub check: bool,
}

/// Refreshes `forks/uucore/locales/utils` from the registry cache.
pub fn run_locales(cmd: &VendorLocalesCommand, _verbose: bool) -> Result<()> {
    let sources = locate_utility_locales(&cmd.version);
    anyhow::ensure!(
        !sources.is_empty(),
        "no uu_*-{} crates with locales in the registry cache; build with \
         `--features coreutils.all` first so cargo unpacks them",
        cmd.version
    );

    let dest_root = PathBuf::from(VENDORED_LOCALES);
    if cmd.check {
        let have = existing_locale_utils(&dest_root);
        let want: Vec<String> = sources.iter().map(|(n, _)| n.clone()).collect();
        anyhow::ensure!(
            have == want,
            "vendored locales are stale: {} utilities on disk, {} in the registry.\n\
             Run `cargo xtask vendor-locales` and commit the result.",
            have.len(),
            want.len()
        );
        eprintln!("vendored locales up to date ({} utilities)", want.len());
        return Ok(());
    }

    // Replace wholesale: a utility dropped upstream must disappear here too, or
    // the fork embeds a catalog for something that no longer exists.
    if dest_root.exists() {
        std::fs::remove_dir_all(&dest_root)
            .with_context(|| format!("clearing {}", dest_root.display()))?;
    }

    let mut files = 0usize;
    for (util, dir) in &sources {
        let dest = dest_root.join(util);
        std::fs::create_dir_all(&dest).with_context(|| format!("creating {}", dest.display()))?;
        let mut entries: Vec<PathBuf> = std::fs::read_dir(dir)
            .with_context(|| format!("reading {}", dir.display()))?
            .filter_map(|e| e.ok().map(|e| e.path()))
            .filter(|p| p.extension().is_some_and(|e| e == "ftl"))
            .collect();
        entries.sort();
        for src in entries {
            let Some(name) = src.file_name() else {
                continue;
            };
            std::fs::copy(&src, dest.join(name))
                .with_context(|| format!("copying {}", src.display()))?;
            files += 1;
        }
    }

    eprintln!(
        "vendored {files} locale file(s) for {} utilities into {}",
        sources.len(),
        dest_root.display()
    );
    Ok(())
}

/// Every `uu_<util>-<version>` in the registry cache that ships a `locales/`
/// directory, as `(utility name, locales dir)` sorted by name.
fn locate_utility_locales(version: &str) -> Vec<(String, PathBuf)> {
    let home =
        std::env::var_os("CARGO_HOME").map_or_else(|| dirs_home().join(".cargo"), PathBuf::from);
    let registry_src = home.join("registry/src");
    let mut out: Vec<(String, PathBuf)> = Vec::new();
    let Ok(roots) = std::fs::read_dir(&registry_src) else {
        return out;
    };
    for root in roots.flatten() {
        let Ok(entries) = std::fs::read_dir(root.path()) else {
            continue;
        };
        for entry in entries.flatten() {
            let name = entry.file_name();
            let dir_name = name.to_string_lossy();
            let Some(rest) = dir_name.strip_prefix("uu_") else {
                continue;
            };
            let Some(util) = rest.strip_suffix(&format!("-{version}")) else {
                continue;
            };
            let locales = entry.path().join("locales");
            if locales.is_dir() {
                out.push((util.to_string(), locales));
            }
        }
    }
    out.sort();
    out.dedup_by(|a, b| a.0 == b.0);
    out
}

/// The utility names currently vendored under `dest_root`, sorted.
fn existing_locale_utils(dest_root: &Path) -> Vec<String> {
    let mut have: Vec<String> = match std::fs::read_dir(dest_root) {
        Ok(entries) => entries
            .flatten()
            .filter(|e| e.path().is_dir())
            .map(|e| e.file_name().to_string_lossy().into_owned())
            .collect(),
        Err(_) => Vec::new(),
    };
    have.sort();
    have
}

/// Runs the vendor-fork command.
pub fn run(cmd: &VendorCommand, verbose: bool) -> Result<()> {
    let src = locate_crate(&cmd.crate_name, cmd.version.as_deref())?;
    eprintln!("vendoring {} from {}", cmd.crate_name, src.display());

    let dest = PathBuf::from("forks").join(&cmd.crate_name);
    if dest.exists() {
        anyhow::bail!("{} already exists; remove it to re-vendor", dest.display());
    }

    copy_lib_sources(&src, &dest, declares_build_script(&src)?)?;
    write_manifest(&src, &dest, &cmd.crate_name)?;
    install_test_session(&src, &dest)?;
    ensure_lock_ignored(&dest)?;

    if cmd.no_codemod {
        eprintln!(
            "vendored (codemod skipped). Run `cargo xtask codemod {}`",
            dest.join("src").display()
        );
        return Ok(());
    }

    eprintln!("routing filesystem access...");
    codemod::run(
        &CodemodCommand {
            path: dest.join("src"),
            check: false,
            skips: Vec::new(),
        },
        verbose,
    )?;

    eprintln!(
        "\nvendored {} into {}. Repoint its dependency in \
         brush-coreutils-builtins/Cargo.toml to `path = \"../forks/{}\"`.",
        cmd.crate_name,
        dest.display(),
        cmd.crate_name
    );
    Ok(())
}

/// Finds a crate's extracted source in the cargo registry cache.
fn locate_crate(name: &str, version: Option<&str>) -> Result<PathBuf> {
    let home =
        std::env::var_os("CARGO_HOME").map_or_else(|| dirs_home().join(".cargo"), PathBuf::from);
    let mut roots = Vec::new();
    let registry_src = home.join("registry/src");
    if let Ok(entries) = std::fs::read_dir(&registry_src) {
        for entry in entries.flatten() {
            if entry.path().is_dir() {
                roots.push(entry.path());
            }
        }
    }
    anyhow::ensure!(
        !roots.is_empty(),
        "no registry source cache under {}; run a build that depends on {name} first",
        registry_src.display()
    );

    let mut best: Option<(String, PathBuf)> = None;
    for root in roots {
        for entry in
            std::fs::read_dir(&root).with_context(|| format!("reading {}", root.display()))?
        {
            let entry = entry?;
            let file_name = entry.file_name();
            let dir_name = file_name.to_string_lossy();
            let Some(ver) = dir_name.strip_prefix(&format!("{name}-")) else {
                continue;
            };
            if let Some(want) = version {
                if ver == want {
                    return Ok(entry.path());
                }
                continue;
            }
            // Newest by string is good enough for the 0.x line the forks pin;
            // an exact version can always be given with --version.
            let is_better = best.as_ref().is_none_or(|(b, _)| ver > b.as_str());
            if is_better {
                best = Some((ver.to_string(), entry.path()));
            }
        }
    }

    best.map(|(_, p)| p).with_context(|| {
        format!("{name} is not in the registry cache; add it as a dependency and build first")
    })
}

/// A best-effort home directory for locating the default cargo cache.
fn dirs_home() -> PathBuf {
    std::env::var_os("HOME").map_or_else(|| PathBuf::from("/"), PathBuf::from)
}

/// Reports the `build` script a manifest declares, if any.
///
/// `uucore` is the first fork with one, and a manifest that names a build
/// script the fork does not carry fails to build with a bare `couldn't read
/// build.rs`. The manifest key is authoritative rather than the file's
/// presence: cargo's default is `build.rs`-if-present, but the normalized
/// registry manifest always states it explicitly.
fn declares_build_script(src: &Path) -> Result<Option<String>> {
    let original = std::fs::read_to_string(src.join("Cargo.toml"))
        .with_context(|| format!("reading {}/Cargo.toml", src.display()))?;
    let manifest: toml::Table = original.parse().context("parsing upstream Cargo.toml")?;
    let Some(toml::Value::Table(package)) = manifest.get("package") else {
        return Ok(None);
    };
    Ok(match package.get("build") {
        Some(toml::Value::String(path)) => Some(path.clone()),
        _ => None,
    })
}

/// Copies the crate's library sources, locales, license and build script into
/// the fork.
///
/// Deliberately omits `src/main.rs` (the binary) and `benches/`: the fork ships
/// as a library, and a binary target would pull in deps the fork does not need.
///
/// Upstream's own `#[cfg(test)]` modules *are* carried, and their
/// dev-dependencies are kept by [`write_manifest`], because D13 makes the
/// upstream suites a health metric -- a fork whose tests cannot compile has no
/// baseline to compare a rebase against.
fn copy_lib_sources(src: &Path, dest: &Path, build_script: Option<String>) -> Result<()> {
    let src_dir = src.join("src");
    anyhow::ensure!(src_dir.is_dir(), "{} has no src/", src.display());
    copy_tree(&src_dir, &dest.join("src"), &|p| {
        // Skip the binary entrypoint; the lib is what we build.
        p.file_name().is_some_and(|n| n == "main.rs")
    })?;

    let locales = src.join("locales");
    if locales.is_dir() {
        copy_tree(&locales, &dest.join("locales"), &|_| false)?;
    }
    // Test fixtures. Upstream's own suite is D13's health metric, and a suite
    // whose fixtures are missing reports failures that say nothing about the
    // routing -- `findutils` reads `test_data/` from the crate root and every
    // one of its filesystem tests fails without it.
    for fixtures in ["test_data", "testdata", "fixtures"] {
        let from = src.join(fixtures);
        if from.is_dir() {
            copy_tree(&from, &dest.join(fixtures), &|_| false)?;
        }
    }

    for aux in ["LICENSE", "LICENSE-MIT", "COPYING"] {
        let from = src.join(aux);
        if from.is_file() {
            std::fs::create_dir_all(dest)?;
            std::fs::copy(&from, dest.join(aux))?;
        }
    }

    if let Some(build) = build_script {
        let from = src.join(&build);
        anyhow::ensure!(
            from.is_file(),
            "{} declares build = {build:?} but {} does not exist",
            src.display(),
            from.display()
        );
        let to = dest.join(&build);
        if let Some(parent) = to.parent() {
            std::fs::create_dir_all(parent)?;
        }
        std::fs::copy(&from, &to)
            .with_context(|| format!("copying build script {}", from.display()))?;
    }
    Ok(())
}

/// Recursively copies `.rs` and asset files, applying a skip predicate.
fn copy_tree(from: &Path, to: &Path, skip: &dyn Fn(&Path) -> bool) -> Result<()> {
    std::fs::create_dir_all(to).with_context(|| format!("creating {}", to.display()))?;
    for entry in std::fs::read_dir(from).with_context(|| format!("reading {}", from.display()))? {
        let entry = entry?;
        let path = entry.path();
        if skip(&path) {
            continue;
        }
        let target = to.join(entry.file_name());
        if path.is_dir() {
            copy_tree(&path, &target, skip)?;
        } else {
            std::fs::copy(&path, &target).with_context(|| format!("copying {}", path.display()))?;
        }
    }
    Ok(())
}

/// Generates the fork manifest from the registry manifest: drops the binary,
/// benches and upstream lint config, and adds the `brush-vfs` dependency.
///
/// `dev-dependencies` are deliberately **kept**. They were dropped originally
/// because the leaf forks did not use them, but that made the fork's own
/// `cargo test` fail to compile -- `uucore`'s test modules use `tempfile`
/// throughout -- and D13's health metric is precisely "do upstream's tests
/// still pass". A fork that cannot run them has no baseline.
fn write_manifest(src: &Path, dest: &Path, name: &str) -> Result<()> {
    let original = std::fs::read_to_string(src.join("Cargo.toml"))
        .with_context(|| format!("reading {}/Cargo.toml", src.display()))?;
    let mut manifest: toml::Table = original.parse().context("parsing upstream Cargo.toml")?;

    // A library fork: no binary, no benches, and no upstream lint table (the
    // fork is excluded from the workspace and its code is not held to brush's
    // lints -- see the root `[workspace] exclude`).
    // Note `test` here strips `[[test]]` *targets*, whose files live in a
    // `tests/` directory the fork does not vendor. Inline `#[cfg(test)]`
    // modules are part of the lib target and are unaffected.
    for key in ["bin", "bench", "example", "test", "badges"] {
        manifest.remove(key);
    }
    // `lints.workspace = true` would resolve against *our* workspace, which the
    // fork is not a member of; upstream's own lint levels are irrelevant here.
    manifest.remove("lints");

    // `[lib] test = false` is upstream saying "my tests are not in this target"
    // -- true there, where they live in a workspace `tests/` directory, and
    // false here, where the fork carries only the lib and everything testable
    // is inside it. Left in place it does not merely skip tests: `cargo test`
    // finds no target at all, compiles *nothing*, and exits 0, so the fork
    // counts as green in D13's health metric while its inline `cfg(test)`
    // modules and the generated identity session are never even built.
    if let Some(toml::Value::Table(lib)) = manifest.get_mut("lib") {
        lib.remove("test");
    }

    if let Some(toml::Value::Table(package)) = manifest.get_mut("package") {
        // The README is not vendored, so a reference to it would fail to package.
        package.remove("readme");
        // `default-run` names a `[[bin]]` that has just been dropped, and cargo
        // refuses to parse a manifest whose default-run target does not exist.
        // `uutils/sed` sets it.
        package.remove("default-run");
        package.insert("autobins".into(), toml::Value::Boolean(false));
        package.insert("autobenches".into(), toml::Value::Boolean(false));
        package.insert("autoexamples".into(), toml::Value::Boolean(false));
        package.insert("autotests".into(), toml::Value::Boolean(false));
    }

    // The fork's own test binary needs `ctor` to install the identity session
    // before upstream's tests run; see `install_test_session`. Dev-only, so it
    // never enters a shipped graph -- unless upstream already brought its own,
    // in which case adding a second is harmful; see `declares_ctor`.
    if !declares_ctor(&manifest) {
        let mut ctor_dep = toml::Table::new();
        ctor_dep.insert("version".into(), toml::Value::String("0.8".into()));
        if let Some(toml::Value::Table(dev)) = manifest.get_mut("dev-dependencies") {
            dev.insert("ctor".into(), toml::Value::Table(ctor_dep));
        } else {
            let mut dev = toml::Table::new();
            dev.insert("ctor".into(), toml::Value::Table(ctor_dep));
            manifest.insert("dev-dependencies".into(), toml::Value::Table(dev));
        }
    }

    // Add the facade the codemod's output depends on.
    let mut vfs_dep = toml::Table::new();
    vfs_dep.insert("path".into(), toml::Value::String(BRUSH_VFS_PATH.into()));
    if let Some(toml::Value::Table(deps)) = manifest.get_mut("dependencies") {
        deps.insert("brush-vfs".into(), toml::Value::Table(vfs_dep));
    } else {
        let mut deps = toml::Table::new();
        deps.insert("brush-vfs".into(), toml::Value::Table(vfs_dep));
        manifest.insert("dependencies".into(), toml::Value::Table(deps));
    }

    let header = format!(
        "# Fork of {name}, vendored from crates.io by `cargo xtask vendor-fork`.\n\
         #\n\
         # Generated, not maintained (D13): pristine upstream is the baseline and the\n\
         # filesystem-routing diff is applied by the codemod. Not a workspace member\n\
         # (see the root `[workspace] exclude`); its routing is proven by the Landlock\n\
         # test (D41), not the ban (D3).\n\n"
    );
    let body = toml::to_string_pretty(&manifest).context("serializing fork Cargo.toml")?;
    std::fs::write(dest.join("Cargo.toml"), format!("{header}{body}"))
        .with_context(|| format!("writing {}/Cargo.toml", dest.display()))?;
    Ok(())
}

/// The `#[cfg(test)]` module every fork carries, and its `mod` declaration.
///
/// Routed production code calls a facade that **fails closed**: with no session
/// installed it refuses every access. That is correct in production and is not
/// negotiable. But upstream's own tests call those routed functions directly and
/// `cargo test` installs nothing, so without this a fork's suite fails wholesale
/// -- and D13 makes that suite the health metric, so a metric reporting dozens
/// of permanent failures measures nothing.
///
/// It cannot weaken production, and the reason is stronger than a runtime guard:
/// `cfg(test)` is enabled only when compiling *this crate's own* test harness,
/// never when a consumer builds it as a dependency. The code is absent from a
/// shipped binary rather than disabled in it, and `ctor` is a dev-dependency
/// that never enters a shipped graph.
///
/// The session installed is the *identity* policy, so routed calls behave
/// exactly as the unrouted ones did and upstream's assertions stay meaningful.
/// It confines nothing, which is right for a test of upstream's logic;
/// confinement is proven separately by `brush-vfs`'s escape suite and by
/// `brush-coreutils-builtins/tests/routing.rs`, which install restrictive
/// policies on purpose.
const TEST_SESSION_MODULE: &str = r"// SEAHAVEN DIVERGENCE, generated by `cargo xtask vendor-fork`.
//
// Installs an identity vfs session before this crate's own test binary runs, so
// upstream's tests keep exercising the routed code instead of failing closed.
// `cfg(test)` means it is absent from every production build -- not disabled in
// one. See `plans/2026-08-18-uucore-fork.md`.

/// Installs the identity session before any test runs.
///
/// A constructor rather than a per-test call because upstream's test bodies are
/// not ours to edit (D13): the marker for a deliberate divergence belongs
/// outside the case.
#[ctor::ctor]
fn install_identity_session_for_tests() {
    let Ok(mounts) = brush_vfs::Policy::identity() else {
        return;
    };
    let mut session = brush_vfs::Session::new(std::sync::Arc::new(brush_vfs::Vfs::new(mounts)));
    if let Ok(cwd) = std::env::current_dir() {
        let _ = session.set_cwd(&cwd.to_string_lossy());
    }
    brush_vfs::ambient::install(session);
}
";

/// Whether the manifest already declares `ctor` in a form the fork's own test
/// binary can use.
///
/// Upstream sometimes depends on it directly -- `uutils/sed` does, at 0.6.
/// Adding a second, semver-incompatible copy puts two `ctor` rlibs in the test
/// target's graph and rustc refuses to choose between them (E0464), so the
/// fork's entire suite stops compiling. That failure is quieter than it sounds:
/// `cargo xtask check forks` counts failing test *names*, and a crate that
/// never builds reports none, so the fork reads as passing while running
/// nothing at all.
///
/// The version does not matter, only the presence: `#[ctor::ctor]` on a free
/// function is spelled the same across every release the forks pull in.
///
/// An `optional` dependency does not count. It is absent unless a feature turns
/// it on, so the generated module could not name it.
fn declares_ctor(manifest: &toml::Table) -> bool {
    /// Whether a `[dependencies]`-shaped table carries a usable `ctor`.
    fn usable(table: &toml::Table) -> bool {
        match table.get("ctor") {
            None => false,
            // The `ctor = { version = "..", optional = true }` form.
            Some(toml::Value::Table(dep)) => {
                dep.get("optional") != Some(&toml::Value::Boolean(true))
            }
            // The `ctor = "0.6"` shorthand, which cannot be optional.
            Some(_) => true,
        }
    }

    const KINDS: [&str; 2] = ["dependencies", "dev-dependencies"];

    let direct = KINDS
        .iter()
        .filter_map(|kind| manifest.get(*kind))
        .filter_map(toml::Value::as_table)
        .any(usable);

    // `[target.'cfg(..)'.dependencies]` is the same declaration behind a cfg.
    // A fork built for one platform still collides on that platform.
    direct
        || manifest
            .get("target")
            .and_then(toml::Value::as_table)
            .is_some_and(|targets| {
                targets
                    .values()
                    .filter_map(toml::Value::as_table)
                    .flat_map(|table| KINDS.iter().filter_map(move |kind| table.get(*kind)))
                    .filter_map(toml::Value::as_table)
                    .any(usable)
            })
}

/// Declaration prepended to the fork's library root.
const TEST_SESSION_DECL: &str = r"
// SEAHAVEN DIVERGENCE: identity vfs session for this crate's own tests.
#[cfg(test)]
mod seahaven_test_session;
";

/// Writes the test-session module and declares it from the library root.
fn install_test_session(src: &Path, dest: &Path) -> Result<()> {
    let lib_rel = lib_path(src)?;
    let lib = dest.join(&lib_rel);
    anyhow::ensure!(
        lib.is_file(),
        "fork library root {} is missing",
        lib.display()
    );

    let module_dir = lib.parent().unwrap_or(dest);
    std::fs::write(
        module_dir.join("seahaven_test_session.rs"),
        TEST_SESSION_MODULE,
    )?;

    let existing = std::fs::read_to_string(&lib)?;
    let at = after_inner_attributes(&existing);
    let (head, tail) = existing.split_at(at);
    std::fs::write(&lib, format!("{head}{TEST_SESSION_DECL}{tail}"))
        .with_context(|| format!("declaring the test session in {}", lib.display()))?;
    Ok(())
}

/// The byte offset just past a file's leading comments and inner attributes.
///
/// `#![..]` must precede every item in a file, so a `mod` declaration cannot
/// simply be prepended -- `uu_csplit` failed to parse as Rust when it was.
/// Bracket depth is tracked because an inner attribute may span lines, as
/// `#![doc = ..]` lists often do.
fn after_inner_attributes(source: &str) -> usize {
    let mut offset = 0usize;
    let mut depth = 0i32;
    for line in source.split_inclusive('\n') {
        let trimmed = line.trim_start();
        let continuing = depth > 0;
        let leading = trimmed.is_empty() || trimmed.starts_with("//") || trimmed.starts_with("#!");
        if !continuing && !leading {
            break;
        }
        if continuing || trimmed.starts_with("#!") {
            depth += i32::try_from(line.matches('[').count()).unwrap_or(0);
            depth -= i32::try_from(line.matches(']').count()).unwrap_or(0);
            depth = depth.max(0);
        }
        offset += line.len();
    }
    offset
}

/// The crate's library root, relative to the crate directory.
fn lib_path(src: &Path) -> Result<PathBuf> {
    let manifest: toml::Table = std::fs::read_to_string(src.join("Cargo.toml"))?
        .parse()
        .context("parsing upstream Cargo.toml")?;
    if let Some(toml::Value::Table(lib)) = manifest.get("lib")
        && let Some(toml::Value::String(path)) = lib.get("path")
    {
        return Ok(PathBuf::from(path));
    }
    Ok(PathBuf::from("src/lib.rs"))
}

/// Writes a `.gitignore` so the fork's standalone `Cargo.lock` is not committed.
fn ensure_lock_ignored(dest: &Path) -> Result<()> {
    std::fs::write(dest.join(".gitignore"), "Cargo.lock\n")
        .with_context(|| format!("writing {}/.gitignore", dest.display()))?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::declares_ctor;

    fn manifest(text: &str) -> toml::Table {
        text.parse().expect("fixture manifest parses")
    }

    #[test]
    fn a_manifest_without_ctor_wants_the_dev_dependency() {
        assert!(!declares_ctor(&manifest(
            "[dependencies]\nlibc = \"0.2\"\n"
        )));
    }

    #[test]
    fn an_upstream_dependency_is_reused() {
        // `uutils/sed`'s own manifest, reduced to the line that matters.
        assert!(declares_ctor(&manifest(
            "[dependencies.ctor]\nversion = \"0.6.0\"\n"
        )));
    }

    #[test]
    fn the_shorthand_form_is_recognized() {
        assert!(declares_ctor(&manifest(
            "[dev-dependencies]\nctor = \"0.8\"\n"
        )));
    }

    #[test]
    fn a_platform_gated_dependency_is_recognized() {
        assert!(declares_ctor(&manifest(
            "[target.'cfg(unix)'.dependencies.ctor]\nversion = \"0.6.0\"\n"
        )));
    }

    #[test]
    fn an_optional_dependency_does_not_count() {
        // Off unless a feature turns it on, so the generated module could not
        // name it and the fork still needs its own.
        assert!(!declares_ctor(&manifest(
            "[dependencies.ctor]\nversion = \"0.6.0\"\noptional = true\n"
        )));
    }
}
